# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    resolvers:
        default:
            web_path: ~
    filter_sets:
        article_thumb:
            quality: 75
            filters:
                thumbnail:
                    size: [300, 200]
                    mode: outbound
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
