vich_uploader:
    db_driver: orm

    mappings:
        ave_image:
            uri_prefix: /images/aves
            upload_destination: '%kernel.project_dir%/public/images/aves'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
