vich_uploader:
    db_driver: orm

    mappings:
        ave_image:
            uri_prefix: /images/aves
            upload_destination: '%kernel.project_dir%/public/images/aves'
            namer: Vich\UploaderBundle\Naming\OrignameNamer

        fotos_aves:
            uri_prefix: /uploads/fotos/aves
            upload_destination: '%kernel.project_dir%/public/uploads/fotos/aves'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true